#!/bin/sh
clear;
echo "Aguarde enquanto configuro as permissões do /var/www/html/$1";
echo "";
chown -R ribafs:www-data /var/www/html/$1;
find /var/www/html/$1 -type d -exec chmod 775 {} \;
find /var/www/html/$1 -type f -exec chmod 664 {} \;
echo "";
echo "Concluído!";

